scrape_configs:
  - job_name: 'flyai'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '192.168.18.106:8080' ]
        labels:
          application: 'flyai'